### ISSUE TITLE
check_config and reboot takes a lot longer

### ISSUE THREAD

**Issue by Guyohms** [custom-components/breaking_changes#16]
## Version of the custom_component
0.3.3

## Describe the bug
I was having issues with the `check_config` and restarting Home Assistant taking a lot longer than usual to execute and via this issue (https://github.com/home-assistant/home-assistant/issues/26023). We stated that it was a custom component causing this problem. I started tracking the culprit by commenting all my custom components, restarted HA and then everything was fast again: Great

Then I started to uncomment custom component one by one, restarting HA and trying the `check_config` between each move. When I did put the breaking changes component back, the problem came back right away.

For the moment, it's commented and all seems fine.

From the tests I've done, at the moment, if I add `breaking_changes:` to my `configuration.yaml` file, the `check_config` will take 1-2 minutes to finish without even restarting HA. I remove it from the `configuration.yaml` and it's back to 5-10 seconds.

This seems to have started about 2 weeks ago which fits with the 0.3.3 release.

## `custom_updater` configuration
Installed using HACS

## Debug log
Like stated in the home assistant issue, these lines show up in the log at the same time the `check_config` is done.
```text
2019-08-24 16:50:23 INFO (SyncWorker_14) [homeassistant.util.package] Attempting install of integrationhelper==0.2.1
2019-08-24 16:51:05 INFO (SyncWorker_17) [homeassistant.util.package] Attempting install of integrationhelper==0.2.2
```

**Comment by aptonline** [comment]
I can confirm that both configuration validation AND reboots are back to normal speeds since removing the `breaking_changers `custom component. Thanks for the heads up.

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/breaking_changes/releases/tag/0.3.4

**Comment by jdesai61** [comment]
In my case, the ha-wyzesense component was the culprit. Removing it fixed config check taking 2+ minutes. However, I am still not sure why "ha core check" takes considerably longer (30+ seconds) than UI (Configuration -> Server Control -> CHECK CONFIGURATION). The UI takes less than ten seconds

**Comment by miguelrochefort** [comment]
Same problem here since adding the `ha-wyzesense` component today.

**Comment by johntdyer** [comment]
I'm having the same problem
